### ISSUE TITLE
How to use "Planner & Integrations"

### ISSUE THREAD

**Issue by thanhhff** [jesusantguerrero/sunday#62]
Hello jesusantguerrero,
I am trying to try to use 2 functions Planner and Integrations, but I don't know how to use them. Can you tell more details about it?
Thank you !

**Comment by jesusantguerrero** [comment]
The planner and integration are work in progress yet.

Maybe at the end of the month could be ready to use, since I am not having much free time.

But the idea it that at least integrate with Gmail and Calendar to create task from selected emails automatically like Monday.com and Create events from Calendar to list in the planner.

**Comment by thanhhff** [comment]
Thank you,
I am now learning about web programming and your website was very helpful. 
Wish you could finish it soon !

**Comment by jesusantguerrero** [comment]
Thanks,  glad to read that it is helpful for you, for real.
keep it going in your learning path!
